django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path('', include('inventaire.urls')),
]

inventaire/urls.py
from django.urls import path
from .views import (
    ProduitListView,
    ProduitDetailView,
    ProduitCreateView,
    ProduitUpdateView,
    ProduitDeleteView,
    AchatProduitListView,
)
from . import views

urlpatterns = [
    path('', ProduitListView.as_view(), name='inventaire-home'),
    path('produit/achat/', AchatProduitListView.as_view(), name='produit-achat'),
    path('produit/<int:pk>/', ProduitDetailView.as_view(), name='produit-detail'),
    path('produit/new/', ProduitCreateView.as_view(), name='produit-create'),
    path('produit/<int:pk>/update/', ProduitUpdateView.as_view(), name='produit-update'),
    path('produit/<int:pk>/delete/', ProduitDeleteView.as_view(), name='produit-delete'),
    path('about/', views.about, name='inventaire-about'),
]

inventaire/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.urls import reverse


class Produit(models.Model):
    Nom = models.CharField(max_length=100)
    Description = models.TextField()
    Type = models.CharField(max_length=50)
    QuantiteStock = models.IntegerField(validators=[MinValueValidator(0)])
    SeuilMinimum = models.IntegerField(default=0)

    def __str__(self):
        return self.Nom

    def get_absolute_url(self):
        return reverse('produit-detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models

# Create your models here.

inventaire/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Produit
from django.db.models import F


def home(request):
    """ renders inventaire/home.html"""
    context = {
        'produits': Produit.objects.all()
    }
    return render(request, 'inventaire/home.html', context)

class ProduitListView(ListView):
    model = Produit
    context_object_name = 'produits'
    ordering = ['Nom']
    # class-based view, by default, are looking in this path
    # <app>/<model>_<viewtype>.hmtl
    template_name = 'inventaire/home.html'

class ProduitDetailView(LoginRequiredMixin, DetailView):
    model = Produit
    # <app>/<model>_<viewtype>.hmtl
    # inventaire/produit_detail.html

class ProduitCreateView(LoginRequiredMixin, CreateView):
    model = Produit
    fields = ['Nom', 'Description', 'Type', 'QuantiteStock']

class ProduitUpdateView(LoginRequiredMixin, UpdateView):
    model = Produit
    fields = ['Nom', 'Description', 'Type', 'QuantiteStock', 'SeuilMinimum']

class ProduitDeleteView(LoginRequiredMixin, DeleteView):
    model = Produit
    success_url = '/'

class AchatProduitListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    queryset = Produit.objects.filter(QuantiteStock__lte=F('SeuilMinimum'))
    context_object_name = 'produits'
    ordering = ['-QuantiteStock']
    permission_required = 'is_superuser'
    template_name = 'inventaire/produit-achat.html'


def about(request):
    return render(request, 'inventaire/about.html', {'title': 'About'})

users/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def profile(request):
    return render(request, 'users/profile.html')

inventaire/templates/inventaire/about.html
{% extends "inventaire/base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

inventaire/templates/inventaire/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'inventaire/main.css' %}">
    {% if title %}
        <title>Django Inventaire - {{ title }}</title>
    {% else %}
        <title>Django Inventaire</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'inventaire-home' %}">ABC.Inc</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{% url 'inventaire-home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'inventaire-about' %}">About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'produit-create' %}">Nouveau Produit</a>
                  <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>

      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  {{ message }}
                </div>
              {% endfor %}
              {% endif %}
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>ABC.Inc News & Actions</h3>
              <p class='text-muted'>Have a great day!
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendar</li>
                  {% if user.is_superuser %}
                  <li class="list-group-item list-group-item-light">
                    <a href="{% url 'produit-achat' %}">Generate Buy List</a>
                  </li>
                  {% endif %}
                </ul>
              </p>
            </div>
          </div>
        </div>
      </main>

     <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

inventaire/templates/inventaire/home.html
{% extends "inventaire/base.html" %}
{% block content %}
    {% for produit in produits %}
    <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{% url 'produit-detail' produit.id %}">{{ produit.Nom }}</a>
            <small class="text-muted">{{ produit.Description }}</small>
          </div>
          <h4>En stock: {{ produit.QuantiteStock }}</h4>
        </div>
      </article>
    {%  endfor %}
{% endblock content %}

inventaire/templates/inventaire/produit-achat.html
{% extends "inventaire/base.html" %}
{% block content %}
    {% for produit in produits %}
    <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{% url 'produit-detail' produit.id %}">{{ produit.Nom }}</a>
          </div>
          <h5>En stock: {{ produit.QuantiteStock }}</a></h2>
          <h5>Seuil: {{ produit.SeuilMinimum }}</a></h5>
        </div>
      </article>
    {%  endfor %}
{% endblock content %}

inventaire/templates/inventaire/produit_confirm_delete.html
{% extends "inventaire/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Effacer un produit</legend>
                <h2>Etes-vous certain de vouloir effacer ce produit: {{ object.Nom }}?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Oui, certain!</button>
                <a class="btn btn-outline-secondary" href="{% url 'produit-detail' object.id %}">Non</a>
            </div>
        </form>
    </div>
{% endblock content %}

inventaire/templates/inventaire/produit_detail.html
{% extends "inventaire/base.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <h4 class="mr-2">{{ object.Nom }}<h4>
                <small class="text-muted">{{ object.Description }}</small>
            </div>
                <p><h6>Stock: {{ object.QuantiteStock }}</h6></p>
                <p><h5>Seuil: {{ object.SeuilMinimum }}</h5></p>
            <div>
                {% if perms.inventaire.add_produit and perms.inventaire.change_produit %}
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'produit-update' object.id %}">Mettre a Jour</a>
                    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'produit-delete' object.id %}">Effacer</a>                
                {% endif %}
            </div>
        </div>
    </article>
{% endblock content %}

inventaire/templates/inventaire/produit_form.html
{% extends "inventaire/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Gestion Produit</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Enregistrer</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/login.html
{% extends "inventaire/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log in</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Account not working? <a class="ml-2" href="#">Email IT</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "inventaire/base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "inventaire/base.html" %}
{% block content %}
    <h1>Name: {{ user.username }}</h1>
    <h5>Email: {{ user.email }}</h5>
{% endblock content %}